### ISSUE TITLE
c1 value

### ISSUE THREAD

**Issue by indiosse** [tebl/D32-Joystick-Adapter#1]
is that a capacitor at C1 on the board , what is its value ??

**Comment by tebl** [comment]
It's 100nF (0.1uF), it has a pin spacing of 5mm.

ons. 12. mai 2021, 19:04 skrev indiosse ***@***.***>:

**Comment by indiosse** [comment]
Hi

Can I ask what is voltage of the capacitor, also is the purpose just so you can use these lower resistance values ?
As I think usually people use at least 100k resistors

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by tebl** [comment]
The purpose of it is just to keep the power to the IC from fluctuating too
much. The resistor values were just to pick something, 10k seemed to work
well enough. I think you could substitute 100k for the 47k ones, it is the
ratio that matters as long as power consumption is kept below what the port
supports.

ons. 12. mai 2021, 21:17 skrev indiosse ***@***.***>:

**Comment by indiosse** [comment]
Interesting so is the capacitor just an option, not necessary at all for the converter to work?

I

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by tebl** [comment]
It's just good practice to include one, if only to rule it put as a
potential issue. More than likely it'd work fine as long as the cable
between it and the computer isn't on the longer side (10-15cm would
probably be fine).

ons. 12. mai 2021, 21:26 skrev indiosse ***@***.***>:
