### ISSUE TITLE
Built a Rev B joystick adapter but I am getting no signals from it.

### ISSUE THREAD

**Issue by Verault** [tebl/D32-Joystick-Adapter#2]
I built one of your Rev B joystick adapters and cant get any of my joysticks to show a signal through it on any came cart I plug in.
https://photos.app.goo.gl/vmTawGi84eFRXMJB8

Granted I own a tandy color computer. Everything I read online says the joysticks are pin for pin compatible. Following your photos and information I omitted pin 6 on the joystick adapter (which is for secondary fire button only correct?)

Maybe I am uncertain about the jp1 power jumper? Am I supposed to have this jumpered or connect an external power source? Would love to know what I did wrong on this build. Thanks

**Comment by Verault** [comment]
Just curious if there is a simple basic program I can type in to see if the joystick returns any values as well. Might help in diagnosing.

**Comment by tebl** [comment]
There's a small script at
https://github.com/tebl/D32-Joystick-Adapter/blob/main/software/joystick.bas

4066 ICs do break from time to time, so try changing it out if you have an
extra one. Out of a 10-pack from AliExpress/Ebay it is common to have 2-3
broken chips, or they're a wrongly relabelled chip.

man. 26. jun. 2023, 16:16 skrev Verault ***@***.***>:

**Comment by Verault** [comment]
Thank you. I will try my stock of 4066 ics and the test script and report back.

**Comment by tebl** [comment]
JP1 is just in case the joystick has an autofire circuit that require power, most should work without it.

**Comment by Verault** [comment]
Ok I think I made some progress. First off I ran the basic script and it it showing X and Y activity on all of my 4066 (I have 10). However the basic script is blinking strangely. At the top of the program There is the X: line which blinks, next line down is the Y: line which blinks very fast.
Below that is the F: line which blinks so fast I can not really see it at all. I get a glimpse of a value of 0 very briefly but that is it? Is this a PAL vs NTSC timing issue?

So It seems to me as if the fire button is not making a signal. The soldering is good I can trace the #4 pin from the pcb to the din connector pin.  All the game carts I put in say press a button to play and they dont play as the fire button does not seem to work (I am guessing). I have tried 3 different known good joysticks. One with autofire, another a typical atari 2600 style joystick, and a commodore 64 joystick. They all behave the same.

**Comment by tebl** [comment]
The flickering is probably cls command running, then immediately printing.
It's a bit of an eye strain, but it was meant to be quick and fast to type
in.

I linked an article below, it has a different version of the script and may
work better on a Tandy (mine was for a Dragon as those are what I have).

https://homecomputerguy.de/en/2022/01/02/joystick-adapter-for-tandy-color-computer/

man. 26. jun. 2023, 18:45 skrev Verault ***@***.***>:

**Comment by Verault** [comment]
Thanks for the link. I tried the program and it is indeed easier to look at. I also hooked up pin 6 with a bodge wire (in the thinking that maybe the Tandy COCO series is using fire2 instead of fire1 and just knowing all pins are connected. 

With that said I am getting the same results. I have X and Y but the fire button(s) dont register anything on known working joysticks.

Ill side on the thinking that maybe I did something wrong in building this adapter and build a second one to see if I get the same results. This is very odd indeed.

**Comment by Verault** [comment]
Ok. After alot of frustration and troubleshooting I was able to resolve this problem. 
In a nutshell I for some reason swapped pins 4 and 5 from the joystick adapter to the Din cable. 

IT now tests and works great. I will close out the issue but I just wanted to let you know this adapter in fact works great on the Tandy TRS-80 Coco 1 and Coco 2.  I dont own a Coco 3 but I suspect it works fine on those machines. So you can update this repository for future builders. I just finished up testing on my Coco 1 and 2 and it works perfectly.

Thank you!

**Comment by tebl** [comment]
Glad to hear that you got it working. Sometimes the journry to the answer
is worth just as much as the answer, also... you get to play games with it
:-)

tir. 18. jul. 2023, 01:41 skrev Verault ***@***.***>:
